version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: boutaina
      POSTGRES_PASSWORD: fouzia1966
      POSTGRES_DB: unihive
    ports:
      - "5434:5432"

  eventservice:
    image: unihive/eventservice
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/unihive
      SPRING_DATASOURCE_USERNAME: boutaina
      SPRING_DATASOURCE_PASSWORD: fouzia1966

  clubservice:
    image: unihive/clubservice
    depends_on:
      - db
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/unihive
      SPRING_DATASOURCE_USERNAME: boutaina
      SPRING_DATASOURCE_PASSWORD: fouzia1966

  authentification:
        image: unihive/authentification
        depends_on:
          - db
        ports:
          - "8084:8084"
        environment:
          SPRING_PROFILES_ACTIVE: dev
          SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/unihive
          SPRING_DATASOURCE_USERNAME: boutaina
          SPRING_DATASOURCE_PASSWORD: fouzia1966


  apigateway:
      image: unihive/apigateway
      ports:
        - "8082:8082"
