version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: boutaina
      POSTGRES_PASSWORD: fouzia1966
      POSTGRES_DB: unihive
    ports:
      - "5434:5432"  # Map port 5434 on host to port 5432 in the container

  eventservice:
    image: unihive/eventservice
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/unihive  # Use port 5432
      SPRING_DATASOURCE_USERNAME: boutaina
      SPRING_DATASOURCE_PASSWORD: fouzia1966

  apigateway:
      image: unihive/apigateway
      ports:
        - "8081:8081"
