server:
  port: ${PORT:8080}
  error:
    include-message: always

supabase:
  url: https://yfnmatryhthmdluxgbdb.supabase.co
  anon: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmbm1hdHJ5aHRobWRsdXhnYmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA0ODk2MDEsImV4cCI6MjAyNjA2NTYwMX0.4hYSYPs3_bNIuoMVRV023VJv2iMHExnISOCiFPu5V20
  jwt_secret: AndWL5D2oEVYvhWiyTFAm7gN2P/0lpOaL8i4gYXq37u5wOKis5GLuU5tT7AOySYBwFeEF1oq5rxyA/RvR0/uuw==

spring:
  application:
    name: unihive-backend
  datasource:
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres
    username: postgres.yfnmatryhthmdluxgbdb
    password: UniHive575859
    driverClassName: org.postgresql.Driver
    hikari:
      data-source-properties:
        prepareThreshold: 0
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
      show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: info.unihive@gmail.com
    password: adhutlynxawdtvbr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    gcp:
      project-id: unihive-421208
      credentials:
        location: classpath:gcp-account-file.json
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  graphql:
    cors:
      allowed-origins: https://unihive-0bcdbacd92b4.herokuapp.com
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
gcp:
  bucket:
    name: unihive-files
