server:
  port: ${SERVER_PORT:8081}
  error:
    include-message: always


spring:
  application:
    name: EventService
  datasource:
    url: jdbc:postgresql://db:5432/unihive
    username: boutaina
    password: fouzia1966
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # or create or create-drop depending on your needs
      show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
      show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: info.unihive@gmail.com
    password: adhutlynxawdtvbr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    gcp:
      project-id: unihive-421208
      credentials:
        location: classpath:gcp-account-file.json
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
gcp:
  bucket:
    name: unihive-files
